#!/usr/bin/env python3
"""Generate the minimal TypeScript fixture client contract from FastAPI OpenAPI.

This generator intentionally supports only the bounded WEB-W05 fixture schema.
It fails rather than guessing when the API path, response component, or version
changes. Use ``--check`` in validation and ``--write`` when the contract has an
approved coordinated producer/consumer change.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from onejournal.api.app import app


PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = PROJECT_ROOT / "web/lib/generated/onejournal-api.ts"
EXPECTED_VERSION = "onejournal.web-fixture.v1"


def render() -> str:
    document = app.openapi()
    operation = document["paths"].get("/api/v1/preview", {}).get("get", {})
    schema_ref = operation.get("responses", {}).get("200", {}).get("content", {}).get(
        "application/json", {}
    ).get("schema", {}).get("$ref")
    if schema_ref != "#/components/schemas/PreviewResponse":
        raise ValueError("unexpected preview response schema")
    components = document.get("components", {}).get("schemas", {})
    if "PreviewResponse" not in components or "QualityState" not in components:
        raise ValueError("required fixture schema is absent from OpenAPI")
    return f"""/* This file is generated by scripts/web/generate_fixture_api_client.py. */
/* Source contract: /api/v1/preview ({EXPECTED_VERSION}). Do not edit manually. */

export type QualityState = {{
  status: 'demo' | 'unavailable';
  reason: string;
}};

export type DecimalMetric = {{
  value: string | null;
  currency: 'USD' | null;
  quality: QualityState;
}};

export type PreviewFixture = {{
  metadata: {{
    contract_version: '{EXPECTED_VERSION}';
    mode: 'demo';
    asof: string;
    generated_at: string;
    quality: QualityState;
  }};
  metrics: Record<string, DecimalMetric>;
  notices: string[];
}};
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--check", action="store_true")
    action.add_argument("--write", action="store_true")
    args = parser.parse_args()

    expected = render()
    if args.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            print(f"FAIL generated client drift: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        print("PASS generated fixture client is current")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"WROTE {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
